set mouse=a

execute pathogen#infect()
syntax on
filetype plugin indent on



let g:VimTodoListsUndoneItem = '- [待完成]'
let g:VimTodoListsDoneItem = '- [已完成]'

filetype indent on
set ruler               "打开状态栏标尺
syntax on               "自动语法高亮
" add tab space
set ts=4
set autoindent
set shiftwidth=4        "默认缩进4个空格
set softtabstop=4       "使用tab时 tab空格数
set tabstop=4           "tab 代表4个空格
set expandtab           "使用空格替换tab
set showmatch           "高亮显示匹配的括号
set hlsearch            "高亮显示搜索结果

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

let g:markdown_include_jekyll_support = 0
let g:markdown_enable_folding = 1
let g:markdown_enable_mappings = 0
let g:markdown_enable_insert_mode_leader_mappings = 1
let g:markdown_enable_spell_checking = 0
let g:markdown_enable_input_abbreviations = 0
let g:markdown_enable_conceal = 1

Plugin 'iamcco/markdown-preview.nvim'
nmap <C-p> <Plug>MarkdownPreviewToggle

