" version: vim_plugins_20220803_v1
set mouse=a

" 状态栏
set statusline=%F%=行:%l\ 列:%c\ \ %p%%,%L\ \ 缓:%n\ %r\ %m
set ls=2

"代码行数
set nu

"复制到系统粘贴板
" can use "+y
set clipboard=unnamedplus

filetype indent on
set ruler               "打开状态栏标尺
syntax on               "自动语法高亮
" add tab space
set ts=4
set autoindent
set shiftwidth=4        "默认缩进4个空格
set softtabstop=4       "使用tab时 tab空格数
set tabstop=4           "tab 代表4个空格
set expandtab           "使用空格替换tab
set showmatch           "高亮显示匹配的括号
set hlsearch            "高亮显示搜索结果


let g:VimTodoListsUndoneItem = '- [待完成]'
let g:VimTodoListsDoneItem = '- [已完成]'

" html 2 space
autocmd FileType html setlocal shiftwidth=2 tabstop=2 expandtab
" javascript 2 space
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 expandtab

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"

" NERDTree
call vundle#begin()
  Plugin 'preservim/nerdtree'
call vundle#end()

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>


Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'


let g:markdown_include_jekyll_support = 0
let g:markdown_enable_folding = 0
let g:markdown_enable_mappings = 0
let g:markdown_enable_insert_mode_leader_mappings = 1
let g:markdown_enable_spell_checking = 0
let g:markdown_enable_input_abbreviations = 0
let g:markdown_enable_conceal = 1
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_folding_level = 6

" code check
Plugin 'dense-analysis/ale'
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'html': ['vscodehtml'],
\   'css': ['stylelint'],
\   'vue': ['eslint', 'vls'],
\   'python': ['pylint']
\}
" In ~/.vim/vimrc, or somewhere similar.
let g:ale_linter_aliases = {'vue': ['vue', 'javascript']}
"let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'


" persistent sessions
Plugin 'thaerkh/vim-workspace'

let g:workspace_autocreate = 0
let g:workspace_autosave_always = 1
nnoremap <leader>s :ToggleWorkspace<CR>
let g:workspace_session_directory = $HOME . '/.vim/sessions/'

" 注意将调用本地浏览器，终端不可用。
Plugin 'iamcco/markdown-preview.nvim'

" example
nmap <C-s> <Plug>MarkdownPreview
nmap <M-s> <Plug>MarkdownPreviewStop
nmap <C-p> <Plug>MarkdownPreviewToggle

" 关闭补全额外的预览窗口
set completeopt=menuone

" pydiction
filetype plugin on
let g:pydiction_location = $HOME . '/.vim/bundle/pydiction/complete-dict'
let g:pydiction_menu_height = 1

" xptemplate
set nocompatible
set rtp+=$HOME/.vim/xptemplate

"python
set tags+=tags

"preview local files
nmap <C-p><C-p> :exec '!exec google-chrome %'<CR>

"https://github.com/jlanzarotta/bufexplorer
Plugin 'jlanzarotta/bufexplorer'


